version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "88:88"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - my-app
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      NODE_ENV: production
